package Syntax;

public enum SyntaxKind{
  EndOfFileToken,
  NumberToken,
  WhitespaceToken,
  PlusToken,
  MinusToken,
  StarToken,
  NegationToken,
  OpenParenthesisToken,
  CloseParenthesisToken,
  ParenthesisExpression,
  BadToken,
  LiteralExpression,
  BinaryExpression,
  TrueKeyword,
  FalseKeyword,
  IdentifierKeyword,
  AndToken,
  CompareToken,
  NameExpression,
  AssignmentExpression,
  EqualsToken,
  SemicolonToken,
  IntTypeKeywork,
  BooleanTypeKeyword,
  AllocationKeyword,
  DeclarationExpression,
  OpenBracketsToken,
  CloseBracketsToken,
  ArrayTypeToken,
  ThisKeyword,
  BracketsExpression,
  AllocationExpression,
  UnaryExpression
}