package Lexicon;

public enum TokenKind {
    EndOfFileToken,
    NumberToken,
    IgnorableToken,
    PlusToken,
    MinusToken,
    StarToken,
    NegationToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    ParenthesisExpression,
    BadToken,
    TrueKeyword,
    FalseKeyword,
    IdentifierKeyword,
    AndToken,
    CompareToken,
    NameExpression,
    EqualsToken,
    SemicolonToken,
    IntTypeKeywork,
    BooleanTypeKeyword,
    AllocationKeyword,
    OpenBracketsToken,
    CloseBracketsToken,
    ArrayTypeToken,
    ThisKeyword,
    DotToken,
    LengthKeyword,
    OpenScopeToken,
    CloseScopeToken,
    CommaToken
}
